# Based on Todd Werth's .bashrc
# See http://blog.infinitered.com/entries/show/4

export OS=`uname -s | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
export OSVERSION=`uname -r`; OSVERSION=`expr "$OSVERSION" : '[^0-9]*\([0-9]*\.[0-9]*\)'`
export MACHINE=`uname -m | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
export PLATFORM="$MACHINE-$OS-$OSVERSION"

if [ "$OS" = "darwin" ] ; then
    export PATH=/opt/local/bin:/opt/local/sbin:/opt/local/Library/Frameworks/Python.framework/Versions/2.6/bin:/opt/local/lib/postgresql84/bin:/opt/local/apache2/bin:/opt/local/lib/mysql5/bin:$PATH  
    export PYTHONPATH=/opt/local/lib/python2.6/site-packages:$PYTHONPATH
    export MANPATH=/opt/local/share/man:$MANPATH
fi

if [ -d ~/bin ]; then
    export PATH=:~/bin:$PATH  # add your bin folder to the path, if you have it.  It's a good place to add all your scripts
fi

export CFLAGS="-I/local/include -I/opt/local/include -L/local/lib -L/opt/local/lib"
export CPPFLAGS="$CFLAGS"
export LDFLAGS="-L/local/lib -L/opt/local/lib"

export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/X11R6/lib/pkgconfig:/local/lib/pkgconfig:/opt/local/lib/pkgconfig"
export ACLOCAL_FLAGS="-I /local/share/aclocal -I /opt/local/share/aclocal -I /usr/share/aclocal"

source ~/.bashrc

echo -e "Kernel Information: " `uname -smr`
echo -ne "${COLOR_GRAY}Uptime: "; uptime
echo -ne "${COLOR_GRAY}Server time is: "; date

