# Based on Todd Werth's .bashrc
# See http://blog.infinitered.com/entries/show/4

export OS=`uname -s | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
export OSVERSION=`uname -r`; OSVERSION=`expr "$OSVERSION" : '[^0-9]*\([0-9]*\.[0-9]*\)'`
export MACHINE=`uname -m | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
export PLATFORM="$MACHINE-$OS-$OSVERSION"

if [ "$OS" = "darwin" ] ; then
    # gentoo prefix
    export EPREFIX=$HOME/Library/gentoo
    # path to python
    export PATH=/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin:$PATH
    # path to databases and apache
    export PATH=/opt/local/lib/postgresql84/bin:/opt/local/apache2/bin:/opt/local/lib/mysql5/bin:$PATH  
    # path to macports stuff
    export PATH=/opt/local/bin:/opt/local/sbin:$PATH
    export PYTHONPATH=/opt/local/lib/python2.7/site-packages:$PYTHONPATH
    export MANPATH=/opt/local/share/man:$MANPATH
    export PERL5LIB=/opt/local/lib/perl5/site_perl/5.12.3:$PERL5LIB
fi

if [ -d ~/bin ]; then
    export PATH=:~/bin:$PATH
fi

export CFLAGS="-I/local/include -I/opt/local/include -L/local/lib -L/opt/local/lib"
export CPPFLAGS="$CFLAGS"
export LDFLAGS="-L/local/lib -L/opt/local/lib"
export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/X11R6/lib/pkgconfig:/local/lib/pkgconfig:/opt/local/lib/pkgconfig"
export ACLOCAL_FLAGS="-I /local/share/aclocal -I /opt/local/share/aclocal -I /usr/share/aclocal"

source ~/.bashrc
