au BufNewFile,BufRead *.pde set filetype=c

set backup
set backupdir=~/.vim/tmp/
silent! set undodir=~/.vim/tmp/
silent! set undofile

set backspace=2
set formatoptions=cornql
set fileformats=unix,dos,mac
set iskeyword+=_,$,@,%,#

set hidden
set nosplitbelow
set splitright

set mouse=a
set noerrorbells
set visualbell

set wildmenu
set wildignore=*.dll,*.o,*.obj,*.bak,*.exe,*.pyc,
                \*.jpg,*.gif,*.png
set wildmode=list:longest

set nohlsearch
set incsearch
set showmatch
set matchtime=5

set nostartofline
set vb t_vb=
set report=0

set number
set numberwidth=5
set ruler
set scrolloff=5
set sidescrolloff=5
set shortmess=aOstT
set showcmd

set laststatus=2
set statusline=%f%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]
"              | | | | |  |   |      |  |     |    |
"              | | | | |  |   |      |  |     |    + current column
"              | | | | |  |   |      |  |     +-- current line
"              | | | | |  |   |      |  +-- current % into file
"              | | | | |  |   |      +-- current syntax in square brackets
"              | | | | |  |   +-- current fileformat
"              | | | | |  +-- number of lines
"              | | | | +-- preview flag in square brackets
"              | | | +-- help flag in square brackets
"              | | +-- readonly flag in square brackets
"              | +-- rodified flag in square brackets
"              +-- full path to file in the buffer

set expandtab " no real tabs please!
set autoindent
set smarttab
set shiftwidth=4 " auto-indent amount when using cindent, >>, << and stuff like that
set softtabstop=4 " when hitting tab or backspace, how many spaces should a tab be (see expandtab)
set tabstop=8 " real tabs should be 8, and they will show with set list on

set ignorecase " case insensitive by default
set infercase " case inferred by default
set smartcase " if there are caps, go case-sensitive
set nowrap " do not wrap line
set shiftround " when at 3 spaces, and I hit > ... go to 4, not 5

set foldmethod=indent
set foldlevel=99

set t_Co=256
set background=dark
colorscheme xoria256-mod
syntax on

if v:version < 700
    finish
endif

if !isdirectory(expand("~/.vim/bundle/vundle/.git"))
    !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
endif

filetype off
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'msanders/snipmate.vim'
Bundle 'tpope/vim-surround'
Bundle 'ervandew/supertab'
Bundle 'mileszs/ack.vim'
Bundle 'tpope/vim-markdown'
Bundle 'scrooloose/nerdcommenter'
Bundle 'fs111/pydoc.vim'
Bundle 'kevinw/pyflakes-vim'
Bundle 'L9'
Bundle 'FuzzyFinder'
Bundle 'minibufexpl.vim'
Bundle 'pep8'
Bundle 'taglist.vim'

let g:pep8_map='<leader>8'

filetype plugin indent on

