#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userdefaults=$HOME/.Xdefaults
usermodmap=$HOME/.Xmodmap

if [ -f $userdefaults ]; then
    xrdb -merge $userdefaults
fi
   
if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

#source ~/.bash_profile

xset b off
xset b 0 0 0

export RXVT_SOCKET=$HOME/.rxvt_socket
# urxvtd -o &

# /opt/local/bin/awesome
